=== amathieson/QMB_Rooms/PHP/QMB_ROOMS.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "timetable_endpoint": {
      "type": "string",
      "format": "uri"
    },
    "rooms": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "modules_endpoint": {
      "type": "string",
      "format": "uri"
    },
    "room_notices": {
      "type": "object",
      "additionalProperties": {
        "type": "string"
      }
    },
    "room_translations": {
      "type": "object",
      "additionalProperties": {
        "type": "string"
      }
    }
  },
  "required": ["timetable_endpoint", "rooms", "modules_endpoint", "room_notices", "room_translations"]
}

=== amathieson/QMB_Rooms/PHP/config.json
{
  "timetable_endpoint": "https://timetable.dundee.ac.uk:8087/reporting/textspreadsheet?objectclass=locations&idtype=id&template=SWSCUST+location+textspreadsheet",
  "rooms": ["9994.0.G03","9994.0.G04","9994.0.G06","9994.0.G11","9994.1.1.12","9994.1.1.13","9994-G.08"],
  "modules_endpoint": "https://www.dundee.ac.uk/module/",
  "room_notices": {
    "Lab 3":"Lab 3 is now a Social Space. No computing facilities available in this room. More spaces are available in Labs 0-2.",
    "Lab 4":"Lab 4 is intended for use by 4th year undergraduates outside of timetabled teaching time. More spaces are available in Labs 0-2.",
    "Lab 5":"Lab 5 is intended for use by TPG students outside of timetabled teaching time. More spaces are available in Labs 0-2.",
    "Seminar Room":"No Computing facilities available in this room, suitable for laptop users."
  },
  "room_translations": {
    "Queen Mother Lab 0 (Ssen Its) (Hts)    [Cap.20]": "Lab 0",
    "Queen Mother Lab 1 (Ssen Its)  (Hts)   [Cap.22]": "Lab 1",
    "Queen Mother Lab 2 (Ssen Its) (Hts)    [Cap.22]": "Lab 2",
    "Queen Mother Lab 3 Student Social Room (Ssen)   [Cap.29]": "Lab 3",
    "Queen Mother Lab 4 (Ssen Its)   [Cap.22]": "Lab 4",
    "Queen Mother Lab 5 (Ssen Its)   [Cap.15]": "Lab 5",
    "Queen Mother Seminar Room G08 (Ssen)   [Cap.28]": "Seminar Room"
  }
}
